spring:
  application:
    name: wakanda-security
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
        
server:
  port: 4919
  
redis:
  url: redis://127.0.0.1:6379/0

info:
  java-vendor: ${java.specification.vendor}
  app:
    name: Wakanda Security
    description: Security microservice to handle authentications
    version: "@project.version@"
